# Generated by Django 5.2.11 on 2026-03-02 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('login', 'Login'), ('logout', 'Logout'), ('settings_change', 'Settings Change'), ('permission_change', 'Permission Change')], max_length=50)),
                ('object_id', models.UUIDField()),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=200)),
                ('details', models.JSONField(default=dict, help_text='Action details and changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Dashboard', max_length=100)),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Dashboard',
                'verbose_name_plural': 'Admin Dashboards',
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple')], default='blue', max_length=20)),
                ('is_private', models.BooleanField(default=True, help_text='Only visible to creator')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Note',
                'verbose_name_plural': 'Admin Notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20)),
                ('for_all_admins', models.BooleanField(default=True)),
                ('action_url', models.URLField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('partial', 'Partial Backup'), ('auto', 'Automated Backup'), ('manual', 'Manual Backup')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('tables_included', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('metric', 'Metric'), ('list', 'List'), ('calendar', 'Calendar')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('area', 'Area Chart'), ('number', 'Number Card')], max_length=20, null=True)),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration')),
                ('data_source', models.CharField(help_text='API endpoint or data source', max_length=200)),
                ('size', models.CharField(choices=[('small', 'Small (1/4)'), ('medium', 'Medium (1/2)'), ('large', 'Large (3/4)'), ('full', 'Full Width')], default='medium', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('roles', models.JSONField(default=list, help_text='User roles that can see this widget')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default widget for all admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField(default=0)),
                ('column', models.PositiveIntegerField(default=0)),
                ('custom_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Widget Placement',
                'verbose_name_plural': 'Widget Placements',
                'ordering': ['row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used to generate this report')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(default='Under Maintenance', max_length=200)),
                ('message', models.TextField(default='We are currently performing maintenance. Please check back soon.')),
                ('allowed_ips', models.JSONField(blank=True, default=list)),
                ('allowed_paths', models.JSONField(blank=True, default=list, help_text='URL paths that remain accessible')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Mode',
                'verbose_name_plural': 'Maintenance Modes',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('inventory', 'Inventory Report'), ('customer', 'Customer Report'), ('product', 'Product Report'), ('payment', 'Payment Report'), ('shipping', 'Shipping Report'), ('tax', 'Tax Report'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, help_text='Report configuration (fields, filters, etc.)')),
                ('available_formats', models.JSONField(default=list, help_text='List of available export formats')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Cron expression or schedule config')),
                ('recipients', models.JSONField(blank=True, default=list, help_text='Email recipients for scheduled reports')),
                ('roles', models.JSONField(default=list, help_text='User roles that can access this report')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System default report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('storage', 'Storage'), ('email', 'Email Service'), ('payment', 'Payment Gateway'), ('sms', 'SMS Service'), ('cdn', 'CDN')], max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in ms', null=True)),
                ('error_rate', models.FloatField(blank=True, help_text='Error rate percentage', null=True)),
                ('message', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('email', 'Email'), ('tax', 'Tax'), ('seo', 'SEO'), ('security', 'Security'), ('features', 'Features'), ('maintenance', 'Maintenance')], default='general', max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON schema for validation')),
                ('options', models.JSONField(blank=True, default=list, help_text='Available options for select type')),
                ('is_editable', models.BooleanField(default=True)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Should be stored encrypted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
